version: '3.3'
services:
  production-nginx:
    container_name: 'nginx'
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./production.conf:/etc/nginx/conf.d/default.conf
      - ./ROOT:/usr/share/nginx/html
      - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/api.youxchange.io/fullchain.pem:/etc/letsencrypt/live/api.youxchange.io/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/api.youxchange.io/privkey.pem:/etc/letsencrypt/live/api.youxchange.io/privkey.pem
