version: '3'

services:
  rails:
    container_name: rails
    hostname: rails
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - 3000:3000

  nginx:
    container_name: nginx
    hostname: nginx
    build:
      context: .
      dockerfile: ./web/Dockerfile
    depends_on:
      - rails
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/app.youxchange.io/fullchain.pem:/etc/letsencrypt/live/app.youxchange.io/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/app.youxchange.io/privkey.pem:/etc/letsencrypt/live/app.youxchange.io/privkey.pem
